all : gr ls

gr : gr_iris gr_rand gr_ecoli

gr_iris : gr_iris_10 gr_iris_20
gr_rand : gr_rand_10 gr_rand_20
gr_ecoli : gr_ecoli_10 gr_ecoli_20

ls : ls_iris ls_rand ls_ecoli

ls_iris : ls_iris_10 ls_iris_20
ls_rand : ls_rand_10 ls_rand_20
ls_ecoli : ls_ecoli_10 ls_ecoli_20

gr_iris_10 :
	python3 src/main.py iris 10 3 gr 11264
	python3 src/main.py iris 10 3 gr 16438
	python3 src/main.py iris 10 3 gr 75645
	python3 src/main.py iris 10 3 gr 79856
	python3 src/main.py iris 10 3 gr 96867

gr_iris_20 :
	python3 src/main.py iris 20 3 gr 11264
	python3 src/main.py iris 20 3 gr 16438
	python3 src/main.py iris 20 3 gr 75645
	python3 src/main.py iris 20 3 gr 79856
	python3 src/main.py iris 20 3 gr 96867

gr_rand_10 :
	python3 src/main.py rand 10 3 gr 11264
	python3 src/main.py rand 10 3 gr 16438
	python3 src/main.py rand 10 3 gr 75645
	python3 src/main.py rand 10 3 gr 79856
	python3 src/main.py rand 10 3 gr 96867

gr_rand_20 :
	python3 src/main.py rand 20 3 gr 11264
	python3 src/main.py rand 20 3 gr 16438
	python3 src/main.py rand 20 3 gr 75645
	python3 src/main.py rand 20 3 gr 79856
	python3 src/main.py rand 20 3 gr 96867

gr_ecoli_10 :
	python3 src/main.py ecoli 10 8 gr 11264
	python3 src/main.py ecoli 10 8 gr 16438
	python3 src/main.py ecoli 10 8 gr 75645
	python3 src/main.py ecoli 10 8 gr 79856
	python3 src/main.py ecoli 10 8 gr 96867

gr_ecoli_20 :
	python3 src/main.py ecoli 20 8 gr 11264
	python3 src/main.py ecoli 20 8 gr 16438
	python3 src/main.py ecoli 20 8 gr 75645
	python3 src/main.py ecoli 20 8 gr 79856
	python3 src/main.py ecoli 20 8 gr 96867

ls_iris_10 :
	python3 src/main.py iris 10 3 ls 11264
	python3 src/main.py iris 10 3 ls 16438
	python3 src/main.py iris 10 3 ls 75645
	python3 src/main.py iris 10 3 ls 79856
	python3 src/main.py iris 10 3 ls 96867

ls_iris_20 :
	python3 src/main.py iris 20 3 ls 11264
	python3 src/main.py iris 20 3 ls 16438
	python3 src/main.py iris 20 3 ls 75645
	python3 src/main.py iris 20 3 ls 79856
	python3 src/main.py iris 20 3 ls 96867

ls_rand_10 :
	python3 src/main.py rand 10 3 ls 11264
	python3 src/main.py rand 10 3 ls 16438
	python3 src/main.py rand 10 3 ls 75645
	python3 src/main.py rand 10 3 ls 79856
	python3 src/main.py rand 10 3 ls 96867

ls_rand_20 :
	python3 src/main.py rand 20 3 ls 11264
	python3 src/main.py rand 20 3 ls 16438
	python3 src/main.py rand 20 3 ls 75645
	python3 src/main.py rand 20 3 ls 79856
	python3 src/main.py rand 20 3 ls 96867

ls_ecoli_10 :
	python3 src/main.py ecoli 10 8 ls 11264
	python3 src/main.py ecoli 10 8 ls 16438
	python3 src/main.py ecoli 10 8 ls 75645
	python3 src/main.py ecoli 10 8 ls 79856
	python3 src/main.py ecoli 10 8 ls 96867

ls_ecoli_20 :
	python3 src/main.py ecoli 20 8 ls 11264
	python3 src/main.py ecoli 20 8 ls 16438
	python3 src/main.py ecoli 20 8 ls 75645
	python3 src/main.py ecoli 20 8 ls 79856
	python3 src/main.py ecoli 20 8 ls 96867
